name: desn366
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50446
title: DESN366 Publication Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f49cc4'
    - '#ffffff'
    - '#4f4e4c'
    - '#e0d93c'
    - '#e32e89'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
