name: desn366
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50181
title: DESN366 Publication Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27162141748704016
  lightness: 0.29619848309084773
  saturation: 0.3255329318344593
  rhythmicContrast: 0.5106602115556598
purpose: []
